input_file: "011307_NYSGRC.fasta"
output: "out.csv"
feature_dir: "feature"
dataset: "CF"

GCmapCrys:
  embedding_aa_dim: 32
  embedding_ss_dim: 32
  fc_dim: 32
  fc_dropout: 0
  mp:
    layers: 3
    edge_feats: "[4,4,4]"
    node_feats: "[16,16,16]"
    multi_heads: "[4,4,4]"
    gat_dropout: "[0,0,0]"
  

checkpoint:
  load_pth: "checkpoint/CF/model.pth"

session:
  device: "cuda:0"
  batch_size: 1

