dataset_dir: "data/CRYS"
model: "GCmapCrys"
feature_dir: "feature"

GCmapCrys:
  embedding_aa_dim: 32
  embedding_ss_dim: 16
  fc_dim: 32
  fc_dropout: 0
  mp:
    layers: 3
    edge_feats: "[4,4,4]"
    node_feats: "[16,16,16]"
    multi_heads: "[4,4,4]"
    gat_dropout: "[0,0,0]"
  
DeepCrystal: "None"

checkpoint:
  load: false
  load_pth: ""
  save_dir: "checkpoint/trainval/GCmapCrys"

session:
  device: "cuda:0"
  max_epochs: 200
  batch_size: 64
  lr: 0.001
  weight_decay: 1.0e-03
